var logos = {
  arstechnica: "http://i.newsapi.org/arstechnica-s.png",
  associatedpress: "http://i.newsapi.org/associated-press-s.png",
  bbcnews: "http://i.newsapi.org/bbc-news-s.png",
  bbcsport: "http://i.newsapi.org/bbc-sport-s.png",
  bild: "http://i.newsapi.org/bild-s.png",
  bloomberg: "http://i.newsapi.org/bloomberg-s.png",
  buzzfeed: "http://i.newsapi.org/buzzfeed-s.png",
  cnbc: "http://i.newsapi.org/cnbc-s.png",
  cnn: "http://i.newsapi.org/cnn-s.png",
  dailymail: "http://i.newsapi.org/daily-mail-s.png",
  engadget: "http://i.newsapi.org/engadget-s.png",
  entertainmentweekly: "http://i.newsapi.org/entertainment-weekly-s.png",
  espn: "http://i.newsapi.org/espn-s.png",
  espncricinfo: "http://i.newsapi.org/espn-cric-info-s.png",
  financialtimes: "http://i.newsapi.org/financial-times-s.png",
  focus: "http://i.newsapi.org/focus-s.png",
  foxsports: "http://i.newsapi.org/fox-sports-s.png",
  googlenews: "http://i.newsapi.org/google-news-s.png",
  hackernews: "http://i.newsapi.org/hacker-news-s.png",
  ign: "http://i.newsapi.org/ign-s.png",
  independent: "http://i.newsapi.org/independent-s.png",
  mashable: "http://i.newsapi.org/mashable-s.png",
  metro: "http://i.newsapi.org/metro-s.png",
  mirror: "http://i.newsapi.org/mirror-s.png",
  nationalgeographic: "http://i.newsapi.org/national-geographic-s.png",
  newscientist: "http://i.newsapi.org/new-scientist-s.png",
  nflnews: "http://i.newsapi.org/nfl-news-s.png",
  polygon: "http://i.newsapi.org/polygon-s.png",
  recode: "http://i.newsapi.org/recode-s.png",
  redditrall: "http://i.newsapi.org/reddit-r-all-s.png",
  reuters: "http://i.newsapi.org/reuters-s.png",
  skynews: "http://i.newsapi.org/sky-news-s.png",
  skysportsnews: "http://i.newsapi.org/sky-sports-news-s.png",
  spiegelonline: "http://i.newsapi.org/spiegel-online-s.png",
  talksport: "http://i.newsapi.org/talksport-s.png",
  techcrunch: "http://i.newsapi.org/techcrunch-s.png",
  techradar: "http://i.newsapi.org/techradar-s.png",
  theguardianuk: "http://i.newsapi.org/theguardian-uk-s.png",
  thehindu: "http://i.newsapi.org/the-hindu-s.png",
  thehuffingtonpost: "http://i.newsapi.org/the-huffington-post-s.png",
  thenewyorktimes: "http://i.newsapi.org/the-newyork-times-s.png",
  thenextweb: "http://i.newsapi.org/the-next-web-s.png",
  thetelegraph: "http://i.newsapi.org/the-telegraph-s.png",
  thetimesofindia: "http://i.newsapi.org/the-times-of-india-s.png",
  theverge: "http://i.newsapi.org/the-verge-s.png",
  thewallstreetjournal: "http://i.newsapi.org/the-wallstreet-journal-s.png",
  thewashingtonpost: "http://i.newsapi.org/the-washington-post-s.png",
  time: "http://i.newsapi.org/time-s.png",
}

export function findSourceLogo(source) {
  for(var k in logos) {
    if(k === source) {
      return logos[k]
    }
  }
}